# app/routes/chatbot_routes.py

from fastapi import APIRouter
from pydantic import BaseModel
from rapidfuzz import process

router = APIRouter()

# Expanded FAQ database
faq = {
    # 📂 Upload Sales Data (Expanded)
    "how to upload sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload excel file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how can I upload sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload my sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "add sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales record": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to submit sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload sales sheet": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales data file upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload my sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "excel sales upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "uploading sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales data upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload sales excel sheet": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload excel sales record": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload my sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload sales sheet": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "excel upload sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "add sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit excel file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload daily sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload monthly sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales form": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales file submit": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit daily sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit monthly sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload daily sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales entry": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales records excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload a sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to send sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload my sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales report file upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales records excel submit": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales record upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales data excel upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit my sales sheet": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how can I submit sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "add daily sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "add sales record excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales entry upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales data input upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload excel for sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload sales excel now": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "send sales excel sheet": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales sheet today": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload daily sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit monthly sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales entry excel upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit my sales record": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload store sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload sales records": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales tracking sheet": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload latest sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload newest sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload my shop sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "daily sales excel upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales sheet excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload today sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload sales excel file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to input sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload latest sales sheet": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload monthly sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload updated sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload shop sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "daily upload sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "monthly upload sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload point of sale excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit shop sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit latest sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "excel sheet sales upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload store sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "send sales data excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "send shop sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "send daily sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload cashier sales record": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales record excel file upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "update sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "uploading sales record": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales file upload excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload purchase sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit daily shop sales": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload outlet sales report": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit outlet sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit uploaded sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit shop sales tracking": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "sales performance file upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "submit sales excel today": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload sales figures excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to submit uploaded sales file": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "how to upload shop sales tracking": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload revenue sales excel": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "upload branch sales data": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",
    "branch sales excel file upload": "Go to Sales ➔ Upload Excel ➔ Select and submit your file.",

     # 📋 Manual Sales Entry (Expanded)
    "how to manually add sales data": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "add sales record manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual data entry sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "add sales data manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual entry for sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales data input": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter daily sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter monthly sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales data manual input": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually submit sales data": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales manual entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual recording of sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales record entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales entry manual mode": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual fill sales data": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "how to input sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual method for sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually entering sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "how to record sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "submit sales data manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales form manual entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "inputting sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales entry manual method": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "add daily sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "add monthly sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "record sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales data input manual": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "fill sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually add daily sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually add monthly sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "submit daily sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales data recording": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "input daily sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "entering sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "adding sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales manual input": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual fill for sales record": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual update of sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter sales records manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually insert sales record": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual add sales record": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "how to do manual sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales sheet entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "submit manual sales sheet": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual fill of sales sheet": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual update sales sheet": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual add to sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual save sales data": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual save sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "fill manual sales record": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual data add sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "how to enter sales record manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual process for sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual daily sales submission": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales data process": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "how to submit sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual mode sales record": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "daily manual sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "monthly manual sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually report sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual recording daily sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually register sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually upload sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales manual data process": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "inputting daily sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "inputting monthly sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual input sales records": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual method daily sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual record daily sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual register sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter sales manually in system": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales add form": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual insert sales data": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter manually sales report": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual sales submission": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales record manual method": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually fill sales form": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter manual sales record": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales input manual submission": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales manual add": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manually fill sales sheet": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual updating sales records": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "submit manual sales records": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual data input sales form": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual capture of sales data": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales data form manual fill": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual upload of sales entries": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual daily entry sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual monthly entry sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "input manual sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual record shop sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "add manually shop sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "submit shop sales manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual shop sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "enter manual shop sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual system sales entry": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "daily manual entry shop sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual process input sales": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales data input manually": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales manual daily input": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "manual input of sales form": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "sales manual update": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",
    "daily sales manually entered": "Go to Sales ➔ Manual Entry ➔ Fill the form ➔ Submit.",

    # 📈 View Sales Reports
   # 📊 View Sales Reports (Expanded)
    "how to view sales reports": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "see my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report check": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "check my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to check sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "check sales performance": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to open sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "open sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "where is my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to find sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "find my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "access sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "get sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to get sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to see sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to review sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report lookup": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "review sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "look at sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report download": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "download sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to download sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report dashboard": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report access": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales history report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view my report sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report screen": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales data view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to open my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "check past sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view previous sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "see past sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to check previous sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales record view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales records report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "open old sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to view my sales performance": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales figures report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view sales tracking": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales tracking report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "check shop sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view my shop sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "open daily sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "daily sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view daily sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view monthly sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "monthly sales report view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "check monthly sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales activity report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "track sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "tracking sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "report for sales data": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "where to see sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "where to see sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales transaction report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales entry report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view sales record report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to read sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "read sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "interpret sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales summary view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales overview report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "get monthly sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "see monthly sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "fetch sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "download my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "see my sales records": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to view store sales": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales info report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales statistics report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "shop sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "branch sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "branch sales view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "regional sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "regional sales view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view company sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "company sales overview": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "overall sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "overall sales summary": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "all sales report view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "show my sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales performance summary": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "summary of sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "print sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "how to print sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "export sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report export": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales data export": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "analyze sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view sales trend report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "trend of sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "trend sales view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales comparison report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "compare sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "compare sales data report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "view multiple sales reports": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales report multiple months": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "multi month sales report": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "sales data summary view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",
    "generate sales report view": "Go to Sales ➔ Reports ➔ Choose the date range and view reports.",


   # 🔐 Logout (Expanded)
    "how to logout": "Click on your profile ➔ Select Logout option.",
    "how to log out": "Click on your profile ➔ Select Logout option.",
    "logout from system": "Click on your profile ➔ Select Logout option.",
    "sign out account": "Click on your profile ➔ Select Logout option.",
    "how to sign out": "Click on your profile ➔ Select Logout option.",
    "sign out from account": "Click on your profile ➔ Select Logout option.",
    "exit my account": "Click on your profile ➔ Select Logout option.",
    "log out of system": "Click on your profile ➔ Select Logout option.",
    "how to exit system": "Click on your profile ➔ Select Logout option.",
    "sign out from dashboard": "Click on your profile ➔ Select Logout option.",
    "logout my profile": "Click on your profile ➔ Select Logout option.",
    "sign out my profile": "Click on your profile ➔ Select Logout option.",
    "logout account": "Click on your profile ➔ Select Logout option.",
    "sign out system": "Click on your profile ➔ Select Logout option.",
    "logout user account": "Click on your profile ➔ Select Logout option.",
    "sign me out": "Click on your profile ➔ Select Logout option.",
    "logout from my account": "Click on your profile ➔ Select Logout option.",
    "how can i logout": "Click on your profile ➔ Select Logout option.",
    "where is logout button": "Click on your profile ➔ Select Logout option.",
    "how to exit account": "Click on your profile ➔ Select Logout option.",
    "leave the system": "Click on your profile ➔ Select Logout option.",
    "exit system": "Click on your profile ➔ Select Logout option.",
    "sign out from app": "Click on your profile ➔ Select Logout option.",
    "logout app": "Click on your profile ➔ Select Logout option.",
    "how to logout from dashboard": "Click on your profile ➔ Select Logout option.",
    "how to logout from website": "Click on your profile ➔ Select Logout option.",
    "signout": "Click on your profile ➔ Select Logout option.",
    "logoff": "Click on your profile ➔ Select Logout option.",
    "log off my account": "Click on your profile ➔ Select Logout option.",
    "end session": "Click on your profile ➔ Select Logout option.",
    "end my session": "Click on your profile ➔ Select Logout option.",
    "how to end session": "Click on your profile ➔ Select Logout option.",
    "how to end login": "Click on your profile ➔ Select Logout option.",
    "finish session": "Click on your profile ➔ Select Logout option.",
    "close session": "Click on your profile ➔ Select Logout option.",
    "sign off account": "Click on your profile ➔ Select Logout option.",
    "sign me off": "Click on your profile ➔ Select Logout option.",
    "signoff": "Click on your profile ➔ Select Logout option.",
    "logout from portal": "Click on your profile ➔ Select Logout option.",
    "signout of portal": "Click on your profile ➔ Select Logout option.",
    "signout from site": "Click on your profile ➔ Select Logout option.",
    "logout from this site": "Click on your profile ➔ Select Logout option.",
    "sign out this site": "Click on your profile ➔ Select Logout option.",
    "exit from dashboard": "Click on your profile ➔ Select Logout option.",
    "how to sign off": "Click on your profile ➔ Select Logout option.",
    "logout website": "Click on your profile ➔ Select Logout option.",
    "sign out of profile": "Click on your profile ➔ Select Logout option.",
    "log out now": "Click on your profile ➔ Select Logout option.",
    "how to logout properly": "Click on your profile ➔ Select Logout option.",
    "where to logout": "Click on your profile ➔ Select Logout option.",
    "where is sign out button": "Click on your profile ➔ Select Logout option.",
    "where to find logout": "Click on your profile ➔ Select Logout option.",
    "how to find logout button": "Click on your profile ➔ Select Logout option.",
    "logout from admin panel": "Click on your profile ➔ Select Logout option.",
    "sign out admin": "Click on your profile ➔ Select Logout option.",
    "signout from dashboard": "Click on your profile ➔ Select Logout option.",
    "log out user profile": "Click on your profile ➔ Select Logout option.",
    "exit profile": "Click on your profile ➔ Select Logout option.",
    "sign out user": "Click on your profile ➔ Select Logout option.",
    "logout user": "Click on your profile ➔ Select Logout option.",
    "exit user account": "Click on your profile ➔ Select Logout option.",
    "logout current session": "Click on your profile ➔ Select Logout option.",
    "sign out current session": "Click on your profile ➔ Select Logout option.",
    "sign out manually": "Click on your profile ➔ Select Logout option.",
    "logout manually": "Click on your profile ➔ Select Logout option.",
    "where logout located": "Click on your profile ➔ Select Logout option.",
    "how to log off": "Click on your profile ➔ Select Logout option.",
    "sign out properly": "Click on your profile ➔ Select Logout option.",
    "how to properly logout": "Click on your profile ➔ Select Logout option.",
    "properly sign out": "Click on your profile ➔ Select Logout option.",
    "end login session": "Click on your profile ➔ Select Logout option.",
    "logout and close": "Click on your profile ➔ Select Logout option.",
    "close and logout": "Click on your profile ➔ Select Logout option.",
    "exit app": "Click on your profile ➔ Select Logout option.",
    "logout from mobile": "Click on your profile ➔ Select Logout option.",
    "logout from pc": "Click on your profile ➔ Select Logout option.",
    "logout from website": "Click on your profile ➔ Select Logout option.",
    "logout from profile": "Click on your profile ➔ Select Logout option.",
    "sign out profile page": "Click on your profile ➔ Select Logout option.",
    "sign out now": "Click on your profile ➔ Select Logout option.",
    "please logout": "Click on your profile ➔ Select Logout option.",
    "exit from system": "Click on your profile ➔ Select Logout option.",
    "leave my account": "Click on your profile ➔ Select Logout option.",
    "sign out fully": "Click on your profile ➔ Select Logout option.",
    "logout safely": "Click on your profile ➔ Select Logout option.",
    "safe logout": "Click on your profile ➔ Select Logout option.",
    "logout completely": "Click on your profile ➔ Select Logout option.",
    "sign out completely": "Click on your profile ➔ Select Logout option.",
    "log out completed": "Click on your profile ➔ Select Logout option.",
    "logout success": "Click on your profile ➔ Select Logout option.",
    "logout safely from system": "Click on your profile ➔ Select Logout option.",
    "where is logout option": "Click on your profile ➔ Select Logout option.",
    "logout user session": "Click on your profile ➔ Select Logout option.",
    "how to logout session": "Click on your profile ➔ Select Logout option.",
    "exit from account": "Click on your profile ➔ Select Logout option.",
    "end account session": "Click on your profile ➔ Select Logout option.",
    "how to signout": "Click on your profile ➔ Select Logout option.",
    "sign out easy": "Click on your profile ➔ Select Logout option.",
    "easy logout": "Click on your profile ➔ Select Logout option.",
    "log out here": "Click on your profile ➔ Select Logout option.",
    "sign out here": "Click on your profile ➔ Select Logout option.",
    "sign out quick": "Click on your profile ➔ Select Logout option.",
    "quick logout": "Click on your profile ➔ Select Logout option.",

  # 🔑 Reset Password (Expanded)
    "how to reset password": "Please contact your system administrator to reset your password.",
    "forgot password help": "Please contact your system administrator to reset your password.",
    "password reset help": "Please contact your system administrator to reset your password.",
    "recover password": "Please contact your system administrator to reset your password.",
    "how to recover password": "Please contact your system administrator to reset your password.",
    "forgot password": "Please contact your system administrator to reset your password.",
    "password recovery help": "Please contact your system administrator to reset your password.",
    "how to reset my password": "Please contact your system administrator to reset your password.",
    "forgot my password": "Please contact your system administrator to reset your password.",
    "reset my password": "Please contact your system administrator to reset your password.",
    "how do I reset password": "Please contact your system administrator to reset your password.",
    "how to change password": "Please contact your system administrator to reset your password.",
    "i forgot my password": "Please contact your system administrator to reset your password.",
    "forgotten password help": "Please contact your system administrator to reset your password.",
    "lost password help": "Please contact your system administrator to reset your password.",
    "lost password reset": "Please contact your system administrator to reset your password.",
    "retrieve password": "Please contact your system administrator to reset your password.",
    "retrieve forgotten password": "Please contact your system administrator to reset your password.",
    "change account password": "Please contact your system administrator to reset your password.",
    "reset password request": "Please contact your system administrator to reset your password.",
    "password change help": "Please contact your system administrator to reset your password.",
    "need to reset password": "Please contact your system administrator to reset your password.",
    "can't remember password": "Please contact your system administrator to reset your password.",
    "cannot remember password": "Please contact your system administrator to reset your password.",
    "forgot password request": "Please contact your system administrator to reset your password.",
    "forgot password assistance": "Please contact your system administrator to reset your password.",
    "need new password": "Please contact your system administrator to reset your password.",
    "new password help": "Please contact your system administrator to reset your password.",
    "how to reset login password": "Please contact your system administrator to reset your password.",
    "reset user password": "Please contact your system administrator to reset your password.",
    "update my password": "Please contact your system administrator to reset your password.",
    "password assistance": "Please contact your system administrator to reset your password.",
    "recover forgotten password": "Please contact your system administrator to reset your password.",
    "how to update password": "Please contact your system administrator to reset your password.",
    "login password reset": "Please contact your system administrator to reset your password.",
    "how to fix password issue": "Please contact your system administrator to reset your password.",
    "fix password problem": "Please contact your system administrator to reset your password.",
    "recover account password": "Please contact your system administrator to reset your password.",
    "change forgotten password": "Please contact your system administrator to reset your password.",
    "reset forgotten password": "Please contact your system administrator to reset your password.",
    "forgot password what to do": "Please contact your system administrator to reset your password.",
    "password reset instructions": "Please contact your system administrator to reset your password.",
    "forgot password solution": "Please contact your system administrator to reset your password.",
    "password reset option": "Please contact your system administrator to reset your password.",
    "how to fix login password": "Please contact your system administrator to reset your password.",
    "lost login password": "Please contact your system administrator to reset your password.",
    "forgot portal password": "Please contact your system administrator to reset your password.",
    "forgot site password": "Please contact your system administrator to reset your password.",
    "forgot system password": "Please contact your system administrator to reset your password.",
    "how to fix forgotten password": "Please contact your system administrator to reset your password.",
    "how to recover login credentials": "Please contact your system administrator to reset your password.",
    "reset lost password": "Please contact your system administrator to reset your password.",
    "lost password fix": "Please contact your system administrator to reset your password.",
    "forgot credentials": "Please contact your system administrator to reset your password.",
    "forgot login credentials": "Please contact your system administrator to reset your password.",
    "recover login info": "Please contact your system administrator to reset your password.",
    "retrieve login credentials": "Please contact your system administrator to reset your password.",
    "forgot profile password": "Please contact your system administrator to reset your password.",
    "profile password reset": "Please contact your system administrator to reset your password.",
    "account password reset": "Please contact your system administrator to reset your password.",
    "portal password reset": "Please contact your system administrator to reset your password.",
    "dashboard password reset": "Please contact your system administrator to reset your password.",
    "system password reset": "Please contact your system administrator to reset your password.",
    "forgot password for account": "Please contact your system administrator to reset your password.",
    "recover lost password": "Please contact your system administrator to reset your password.",
    "help me reset password": "Please contact your system administrator to reset your password.",
    "can’t access account password": "Please contact your system administrator to reset your password.",
    "how to regain password": "Please contact your system administrator to reset your password.",
    "password recovery instructions": "Please contact your system administrator to reset your password.",
    "how to fix password login": "Please contact your system administrator to reset your password.",
    "login reset password": "Please contact your system administrator to reset your password.",
    "change lost password": "Please contact your system administrator to reset your password.",
    "update forgotten password": "Please contact your system administrator to reset your password.",
    "forgot password link": "Please contact your system administrator to reset your password.",
    "send password reset link": "Please contact your system administrator to reset your password.",
    "password reset link request": "Please contact your system administrator to reset your password.",
    "password reset form": "Please contact your system administrator to reset your password.",
    "password assistance needed": "Please contact your system administrator to reset your password.",
    "reset password manually": "Please contact your system administrator to reset your password.",
    "forgot admin password": "Please contact your system administrator to reset your password.",
    "reset admin password": "Please contact your system administrator to reset your password.",
    "forgot user password": "Please contact your system administrator to reset your password.",
    "user password reset": "Please contact your system administrator to reset your password.",
    "forgot website password": "Please contact your system administrator to reset your password.",
    "how to retrieve password": "Please contact your system administrator to reset your password.",
    "get new password": "Please contact your system administrator to reset your password.",
    "forgot credentials password": "Please contact your system administrator to reset your password.",
    "forgot username and password": "Please contact your system administrator to reset your password.",
    "username password recovery": "Please contact your system administrator to reset your password.",
    "reset profile password": "Please contact your system administrator to reset your password.",
    "recover my account password": "Please contact your system administrator to reset your password.",
    "password reset my account": "Please contact your system administrator to reset your password.",
    "how to regain login access": "Please contact your system administrator to reset your password.",
    "lost access password": "Please contact your system administrator to reset your password.",
    "password renewal help": "Please contact your system administrator to reset your password.",
    "password renew request": "Please contact your system administrator to reset your password.",
    "lost login info": "Please contact your system administrator to reset your password.",
    "restore password": "Please contact your system administrator to reset your password.",
    "reset password for system": "Please contact your system administrator to reset your password.",
    "system login password reset": "Please contact your system administrator to reset your password.",

   # 🏷️ Low Stock Check (Expanded)
    "how to check low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "view low stock items": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock rice types": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory low stock check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check stock levels": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to see low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to view low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low inventory items": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock inventory": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "view inventory shortages": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory shortage check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check item stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "find low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to check inventory shortages": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory status check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory stock shortage": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock shortage view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to view inventory stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to find stock shortages": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "where to check low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to find low stock items": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "see stock running low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory running out": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "rice types low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "running out of stock view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory levels low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check which items are low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "items running out": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check stock depletion": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory almost empty": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "find items running low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low quantity stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock overview": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory below minimum": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "minimum stock alert": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock notification": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock alert low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to check stock threshold": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "threshold stock view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory near empty": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory almost finished": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check sales stock shortage": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low availability inventory": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory monitor low items": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "find low inventory products": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to monitor stock levels": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "monitor low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "monitor inventory shortages": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory control low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory control check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "daily stock level view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "daily low stock check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock report low inventory": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "view items near depletion": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check warehouse low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "warehouse low inventory check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "warehouse stock shortage": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "warehouse low stock alert": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check rice inventory levels": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "rice types running out": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "find low rice stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "view shortage in rice types": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock checking": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory status monitor": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory stock alert": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "where is low stock report": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low quantity inventory items": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock running low view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory depletion report": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory alert low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low inventory items check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock deficit view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock deficit check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory alert check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory stock running out": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "view short stock items": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check low availability stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory stock low overview": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low items inventory": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "warehouse stock low report": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "rice stock low report": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory restock check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock list view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock items list": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low quantity items": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "almost out of stock check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "view inventory low stock list": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory monitoring low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "shortage report inventory": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock alert notification": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "stock monitoring low": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "how to find shortage stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory shortage monitor": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory restock needed": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock inventory list": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "daily inventory check": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "daily low stock monitor": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "low stock daily view": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "inventory alert threshold": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "find items low quantity": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "check product low stock": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "monitor stock shortage daily": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",
    "shortage inventory list": "Go to Inventory ➔ Low Stock Monitor ➔ View items below threshold.",

# 📊 Generate Forecast (Expanded)
    "how to generate forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate forecast report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales forecast generation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to create forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create forecast report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales prediction generation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "predict sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast sales data": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate sales prediction": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "make sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales forecasting process": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to make forecast report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "build sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate prediction report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast my sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to predict sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate future sales report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast upcoming sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate next sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create future sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast future sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate expected sales report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast report generation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "prepare forecast report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales projection generation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales projection report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales projection creation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "make future sales projection": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "project future sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales demand forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "demand forecast report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales volume forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to project sales data": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate demand forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate sales demand": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast revenue report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "predict revenue from sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to prepare sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to create sales projection": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales prediction report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate sales trends forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "predict upcoming sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create next month forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate forecast for next month": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales trends forecast generation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to do sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast creation method": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast process for sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast report for sales data": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales performance forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "future sales prediction report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to plan sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate forecast of sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecasting next month's sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to make sales projection": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "next month sales prediction": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecasting sales for month": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast upcoming demand": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "prepare future sales report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create predicted sales report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to predict next month sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast excel generation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "predicting future sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecasting growth in sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to estimate future sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales revenue prediction": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to forecast sales performance": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales forecasting method": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "predict sales amount": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "future sales estimates": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "how to build a sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales prediction excel report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecasting business sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate business sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "business sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecasting product sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate forecast based on sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create product sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast sales numbers": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "estimate future sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecasting upcoming sales data": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "predict monthly sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "monthly sales forecast report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "projected sales forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create forecast for product sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast revenue prediction": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "generate sales output forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "create projection report for sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales output forecasting": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "future sales volume forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "predict customer sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales prediction future report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast total sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales projection estimation": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast excel sheet sales": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales future planning forecast": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast business sales trends": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "forecast sales revenue for business": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
    "sales trend prediction report": "Go to Forecast ➔ Click Generate Forecast ➔ View or Export.",
}

# 🧠 Small talk database
smalltalk = {
    # 👋 Greetings
    "hi": "👋 Hello! How can I assist you today?",
    "hello": "👋 Hello! Feel free to ask me anything.",
    "hey": "👋 Hi there! How can I help?",
    "howdy": "👋 Hello! How can I assist you today?",
    "yo": "👋 Hello! How can I assist you today?",
    "sup": "👋 Hello! How can I assist you today?",
    "heya": "👋 Hello! How can I assist you today?",
    "hiya": "👋 Hello! How can I assist you today?",
    "hey there": "👋 Hello! How can I assist you today?",
    "hello there": "👋 Hello! How can I assist you today?",
    "hi there": "👋 Hello! How can I assist you today?",
    "good day": "👋 Hello! How can I assist you today?",
    "morning": "👋 Good morning! How can I assist?",
    "good morning": "👋 Good morning! How can I assist?",
    "good evening": "🌇 Good evening! What do you need help with?",
    "evening": "🌇 Good evening! What do you need help with?",
    "good afternoon": "👋 Hello! How can I assist you today?",
    "afternoon": "👋 Hello! How can I assist you today?",
    "greetings": "👋 Hello! How can I assist you today?",
    "yo bot": "👋 Hello! How can I assist you today?",
    "hiya bot": "👋 Hello! How can I assist you today?",
    "hello friend": "👋 Hello! How can I assist you today?",
    "hi friend": "👋 Hello! How can I assist you today?",
    "hey assistant": "👋 Hello! How can I assist you today?",
    "hi assistant": "👋 Hello! How can I assist you today?",
    "hello assistant": "👋 Hello! How can I assist you today?",
    "good to see you": "👋 Hello! How can I assist you today?",
    "great to see you": "👋 Hello! How can I assist you today?",
    "long time no see": "👋 Hello! How can I assist you today?",
    "good day bot": "👋 Hello! How can I assist you today?",
    "hello there bot": "👋 Hello! How can I assist you today?",
    "hey chatbot": "👋 Hello! How can I assist you today?",
    "good to talk to you": "👋 Hello! How can I assist you today?",

    # 🙏 Thanks / Appreciation
    "thanks": "🙏 You're welcome!",
    "thank you": "🙏 You're welcome!",
    "cheers": "🙏 You're welcome!",
    "many thanks": "🙏 You're welcome!",
    "thanks a lot": "🙏 You're welcome!",
    "thanks so much": "🙏 You're welcome!",
    "thank you very much": "🙏 You're welcome!",
    "thank you so much": "🙏 You're welcome!",
    "much appreciated": "🙏 You're welcome!",
    "really appreciate it": "🙏 You're welcome!",
    "thx": "🙏 You're welcome!",
    "ty": "🙏 You're welcome!",
    "tysm": "🙏 You're welcome!",
    "tysm!": "🙏 You're welcome!",
    "thank u": "🙏 You're welcome!",
    "thanks mate": "🙏 You're welcome!",
    "thanks buddy": "🙏 You're welcome!",
    "thanks bro": "🙏 You're welcome!",
    "appreciate it": "🙏 You're welcome!",
    "appreciate your help": "🙏 You're welcome!",
    "thank you for helping": "🙏 You're welcome!",
    "thank you for support": "🙏 You're welcome!",
    "thanks for helping": "🙏 You're welcome!",
    "thanks for your help": "🙏 You're welcome!",
    "you're awesome": "🙏 You're welcome!",
    "you're great": "🙏 You're welcome!",
    "you're amazing": "🙏 You're welcome!",
    "good bot": "🙏 Thank you! 😊",
    "awesome bot": "🙏 Thank you! 😊",
    "great job": "🙏 Thank you! 😊",
    "good job": "🙏 Thank you! 😊",
    "nice bot": "🙏 Thank you! 😊",
    "good service": "🙏 You're welcome!",
    "wonderful": "🙏 Thank you! 😊",
    "awesome": "🙏 Thank you! 😊",
    "amazing": "🙏 Thank you! 😊",
    "fantastic": "🙏 Thank you! 😊",
    "brilliant": "🙏 Thank you! 😊",
    "cool": "🙏 Thank you! 😊",
    "cool bot": "🙏 Thank you! 😊",
    "nice work": "🙏 Thank you! 😊",
    "well done": "🙏 Thank you! 😊",
    "you rock": "🙏 Thank you! 😊",
    "much obliged": "🙏 You're welcome!",
    "appreciate your assistance": "🙏 You're welcome!",
    "thank you assistant": "🙏 You're welcome!",
    "thanks assistant": "🙏 You're welcome!",
    "cheers buddy": "🙏 You're welcome!",
    "thank you my friend": "🙏 You're welcome!",
    "bless you": "🙏 You're welcome!",
    "cheers for that": "🙏 You're welcome!",
    "thank you kindly": "🙏 You're welcome!",
    "high five": "🙏 Thank you! ✋",
    "fist bump": "🙏 Thank you! 👊",
    "you did great": "🙏 Thank you! 😊",
    "thank you chatbot": "🙏 You're welcome!",
    "awesome assistant": "🙏 Thank you! 😊",
    "thank you so much assistant": "🙏 You're welcome!",
    "appreciate it a lot": "🙏 You're welcome!",
    "thanks for being here": "🙏 You're welcome!",
    "thank you for assisting": "🙏 You're welcome!",
    "thanks again": "🙏 You're welcome!",
    "thank you again": "🙏 You're welcome!",
}


# 🧩 Synonyms / keyword expansion
synonyms = {
    # 🔐 Logout Synonyms
    "sign out": "logout",
    "log out": "logout",
    "exit account": "logout",
    "logout account": "logout",
    "sign off": "logout",
    "log off": "logout",
    "end session": "logout",
    "leave account": "logout",
    "disconnect account": "logout",
    "close session": "logout",
    
    # 📤 Upload Sales File Synonyms
    "upload file": "upload excel",
    "upload sales file": "upload excel",
    "submit excel": "upload excel",
    "send excel file": "upload excel",
    "post excel file": "upload excel",
    "upload sales document": "upload excel",
    "upload sales sheet": "upload excel",
    "upload spreadsheet": "upload excel",
    "send sales file": "upload excel",
    "submit sales excel": "upload excel",
    
    # 🔑 Reset Password Synonyms
    "forgot password": "reset password",
    "password recovery": "reset password",
    "recover password": "reset password",
    "retrieve password": "reset password",
    "lost password": "reset password",
    "reset forgotten password": "reset password",
    "forgot login password": "reset password",
    "forgot my password": "reset password",
    "change forgotten password": "reset password",
    "lost login password": "reset password",

    # 📉 Low Stock Synonyms
    "low stock": "check low stock",
    "stock running out": "check low stock",
    "out of stock check": "check low stock",
    "stock shortage": "check low stock",
    "inventory low": "check low stock",
    "running low inventory": "check low stock",
    "check shortage stock": "check low stock",
    "low quantity items": "check low stock",
    "inventory stock shortage": "check low stock",
    "stock depletion": "check low stock",

    # 📈 Forecast Report Synonyms
    "forecast report": "generate forecast report",
    "sales forecast report": "generate forecast report",
    "generate forecast": "generate forecast report",
    "create forecast report": "generate forecast report",
    "sales prediction report": "generate forecast report",
    "forecast generation": "generate forecast report",
    "forecast output": "generate forecast report",
    "forecast sales report": "generate forecast report",
    "predict sales report": "generate forecast report",
    "forecasting sales report": "generate forecast report",

    # ➕ Additional Helpful Synonyms
    "sales report": "view sales report",
    "sales reports": "view sales report",
    "sales history": "view sales report",
    "sales performance report": "view sales report",
    "inventory report": "view inventory report",
    "low inventory": "check low stock",
    "inventory depletion": "check low stock",
    "sales data upload": "upload excel",
    "sales file upload": "upload excel",
    "upload sales records": "upload excel",
    "upload store sales": "upload excel",
    "submit sales excel file": "upload excel",
    "send sales data": "upload excel",
    "submit sales document": "upload excel",
    "upload daily sales file": "upload excel",
    "upload monthly sales file": "upload excel",
    "excel sales data submit": "upload excel",

    "reset login password": "reset password",
    "update password": "reset password",
    "change password": "reset password",
    "forgot system password": "reset password",
    "forgot my system password": "reset password",
    "forgot app password": "reset password",
    "lost system login password": "reset password",
    "password reset request": "reset password",
    "reset my account password": "reset password",
    "password assistance": "reset password",

    "sign out of account": "logout",
    "log out now": "logout",
    "logout user": "logout",
    "logout from app": "logout",
    "logout system": "logout",
    "account logout": "logout",
    "exit from system": "logout",
    "leave the app": "logout",
    "disconnect system": "logout",
    "end user session": "logout",

    "forecast sales": "generate forecast report",
    "forecast sales growth": "generate forecast report",
    "create sales forecast": "generate forecast report",
    "sales future prediction": "generate forecast report",
    "generate sales forecast document": "generate forecast report",
    "generate sales projection": "generate forecast report",
    "forecast business sales": "generate forecast report",
    "forecast future sales": "generate forecast report",
    "forecast demand sales": "generate forecast report",
    "predict sales volume": "generate forecast report",
}


# 🛠️ Request model
class QuestionRequest(BaseModel):
    question: str

# 🛠️ Route to ask bot
@router.post("/chatbot/ask")
def ask_bot(request: QuestionRequest):
    q = request.question.lower().strip()

    # ✅ 1. Check Smalltalk first
    if q in smalltalk:
        return {"answer": smalltalk[q]}
    
    # ✅ 2. Keyword expansion
    for key, value in synonyms.items():
        if key in q:
            q = q.replace(key, value)

    # ✅ 3. Handle multi-sentence (split by ".", ",", "?")
    parts = [p.strip() for p in q.replace('?', '.').replace(',', '.').split('.') if p.strip()]

    full_response = []

    for part in parts:
        # Fuzzy match each part individually
        best_match, score, _ = process.extractOne(part, faq.keys())

        if score >= 75:  # Optimal balance
            full_response.append(faq[best_match])
        else:
            matches = process.extract(part, faq.keys(), limit=2)
            suggestions = "\n".join([f"➔ {match[0]}" for match in matches])
            full_response.append(f"❓ Not sure. Maybe you meant:\n{suggestions}")

    final_response = "\n\n".join(full_response)
    return {"answer": final_response}
